kind: ConfigMap
apiVersion: v1
metadata:
  name: alertmanager
  namespace: monitor-sa
data:
  alertmanager.yml: |-
    global:
      resolve_timeout: 5m
      smtp_smarthost: 'smtp.163.com:25'
      smtp_from: 'zsly3n3@163.com'
      smtp_auth_username: 'zsly3n3'
      smtp_auth_password: 'KDXORVGQLKLIDUIL'
      smtp_require_tls: false
    route:
      group_by: ['...']
      group_wait: 30s
      group_interval: 2m
      repeat_interval: 1m
      receiver: default-receiver
    inhibit_rules:
      - source_match:
          severity: 'critical'
        target_match:
          severity: 'warning'
        equal: ['alertname', 'dev', 'instance']
    receivers:
    - name: 'default-receiver'
      email_configs:
      - to: 'wmj@rebornplay.com'
        send_resolved: true
